### ISSUE TITLE
Postgres tests fail with race detection enabled (deck ops counters incorrectly synchronized)

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1324]
The purpose of this task is to ensure that this fix:

https://github.com/Kong/deck/pull/381

Get's included in KIC 2.0 prior to the first beta release, as it resolves a data race in Deck that was found via the KIC 2.0 integration tests.

Acceptance criteria
- [ ] all tests (in particular, the postgres integration test) don't fail with `-race` enabled (at the moment of writing, the postgres test fails)

**Comment by mflendrich** [comment]
resolved in deck 1.7.0 which is in use by kic already

**Comment by shaneutt** [comment]
As it turns out, this did not fix the race condition with postgres integration tests.
